version: '3'

volumes:
  postgres:
  yarn:
  bundle:

services:
  postgres:
    image: postgres:10.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - "3035:3035"
  redis:
    image: redis:4.0-alpine
    command: redis-server
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - redis
      - postgres
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - webpacker
      - redis
      - sidekiq